Fix ViewComponent helper access - use helpers.icon
BUG FIX:
ViewComponents cannot call view helpers directly.
Must use helpers.icon instead of icon.

ERROR:
NoMethodError: undefined method 'icon' for Shadcn::TabsComponent

FIX:
Changed: <%= icon tab.icon, size: 16 %>
To: <%= helpers.icon tab.icon, size: 16 %>

This is a ViewComponent requirement in Rails.
All view helpers must be accessed via helpers proxy.